<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>open-img</AssemblyName>
    <RootNamespace>OpenImage</RootNamespace>
    <ApplicationTitle>Open Image — Native Windows Studio</ApplicationTitle>
    <Version>1.0.1</Version>
    <Company>just-matt-z</Company>
    <Product>Open Image</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
